@echo off
cls
echo Are you sure you want to uninstall KnockoffSnake? [y][n]
set /p confirm=
if %confirm%=="y" (
cd %USERPROFILE%/Desktop
echo Deleting desktop icon...
del KnockoffSnakeDesktop.bat
cd %USERPROFILE%/KnockoffSnake/SnakeRemastered
echo Deleting main file...
del SnakeRemastered.pde
echo Deleting player file...
del Player.pde
echo Deleting coins file...
del Coins.pde
echo Deleting enemy file...
del Enemy.pde
cd Data
echo Deleting coin image...
del CoinImage.jpg
echo Deleting enemy image...
del EnemyImage.jpg
echo Deleting player image...
del PlayerImage.jpg
cd ..
echo Deleting images folder...
rmdir Data
cd ..
echo Deleting program folder...
rmdir SnakeRemastered
echo Deleting launcher...
del KnockoffSnakeLauncher.bat
cd %USERPROFILE%/Downloads/SnakeRemastered
echo Deleting wizard...
del SnakeRemasteredWizard.bat
echo Deleting readme...
del README.md
cd ..
echo Deleting download folder...
rmdir SnakeRemastered
cd %USERPROFILE%/KnockoffSnake
move KnockoffSnakeUninstaller.bat %USERPROFILE%
cd ..
echo Deleting file folder...
rmdir KnockoffSnake
echo Deleting uninstaller...
del KnockoffSnakeUninstaller.bat
)